# Configurables for the MT->MX FTP listener
[mtMxListener]
name = "MT MX Listener 1"
enable = true
# Protocol can be "ftp" or "sftp"
protocol = "ftp"
host = "127.0.0.1"
port = 23
username = "admin"
password = "admin"
# Path to the private key file for SFTP, if using SFTP
pvtKeyPath = ""
# Password for the private key, if applicable
keyPass = ""
pollingInterval = 1.0
# Directory where incoming MT files are placed
inwardFilepath = "/mt/inward/"
# Pattern to match incoming file names
inwardFileNamePattern = ".*"

# Configurables for the MT Server client (used to send files)
[mtClient]
name = "MT MX Client 1"
enable = true
protocol = "ftp"
host = "127.0.0.1"
port = 23
username = "admin"
password = "admin"
pvtKeyPath = ""
keyPass = ""
# Directory where original MT messages are moved after successful processing
bkpSuccessFilepath = "/mt/success/"
# Directory where original MT messages are moved after failed processing
bkpFailedFilepath = "/mt/failed/"
# Directory where original MT messages are moved if processing skipped
bkpSkippedFilepath = "/mt/skipped/"
# Directory where translated MT files are moved
outwardFilepath = "/mt/outward/"
outputFileNamePattern = ".fin"
skippedOutputFileNamePattern = ".xml"

# Configurables for the MX->MT FTP listener
[mxMtListener]
enable = true
name = "MX MT Listener 1"
# Protocol can be "ftp" or "sftp"
protocol = "ftp"
host = "127.0.0.1"
port = 23
username = "admin"
password = "admin"
# Path to the private key file for SFTP, if using SFTP
pvtKeyPath = ""
# Password for the private key, if applicable
keyPass = ""
pollingInterval = 1.0
# Directory where incoming MX files are placed
inwardFilepath = "/mx/inward/"
# Pattern to match incoming file names
inwardFileNamePattern = "(.*).ia|(.*).xml"

# Configurables for the MX Server client (used to send files)
[mxClient]
name = "MX MT Client 1"
enable = true
# Protocol can be "ftp" or "sftp"
protocol = "ftp"
host = "127.0.0.1"
port = 23
username = "admin"
password = "admin"
pvtKeyPath = ""
keyPass = ""
# Directory where original MX messages are moved after successful processing
bkpSuccessFilepath = "/mx/success/"
# Directory where original MX messages are moved after failed processing
bkpFailedFilepath = "/mx/failed/"
# Directory where original MX messages are moved if processing skipped
bkpSkippedFilepath = "/mx/skipped/"
# Directory where translated MX files are moved
outwardFilepath = "/mx/outward/"
outputFileNamePattern = ".xml"
skippedOutputFileNamePattern = ".fin"


[ballerina.log]
level = "DEBUG"
format="json"

[log]
# Path to the dashboard log file
dashboardLogFilePath = "/swiftTranslator/logs/"
# Path to the Ballerina log file
ballerinaLogFilePath = "/swiftTranslator/logs/"


[translator]
supportedMTMessageTypes = [
    "103", "110", "111", "112", "190", "191", "192", "196", "199", "202", "205", "210", "290", "291", "292", "296",
    "299", "900", "910", "940", "942"
]
[translator.mxMtExtension]
preProcess = true
postProcess = true
skippedMsgPostProcess = true
basepath = "http://localhost:9090"

[translator.mtMxExtension]
preProcess = true
postProcess = true
skippedMsgPostProcess = true
basepath = "http://localhost:9090"
